#!/bin/bash

if [[ $# == 1 ]]; then
    RUN_RANGE=$1
elif [[ $# == 2 ]]; then
    RUN_RANGE=$1
    EXPORT_FILE="--export $2"
else
    echo "Usage: $0 <run> [ExportFile]"
    exit 1
fi

# script configuration
EXEC_FILE="./BitTorrent" # path to the simulation executable
INI_FILE="../simulations/MultiplePeers.ini" # path to the configuration file
#CONFIG="ThruputStudy" # name of the configuration
CONFIG="MultiplePeers" # name of the configuration
ENV="Cmdenv" # Command environment
#ENV="Tkenv" # TK environment
LOG_DIR="./logs/run_$1"
ERR_FILE="err.log" # the log file where all error messages will be written
OUT_FILE="out.log" # the log file where all log messages will be written
PWD=pwd # the directory where this script is called

# error if the executable file don't exist
if [ ! -e $EXEC_FILE ]
then
    echo "Executable file \"$EXEC_FILE\" not found."
    exit 1;
fi

# error if the config file don't exist
if [ ! -e $INI_FILE ]
then
    echo "Initaliazation file \"$INI_FILE\" not found."
    exit 1;
fi

opp_runall $EXPORT_FILE -j8 $EXEC_FILE -f $INI_FILE -u Cmdenv -c $CONFIG -r $RUN_RANGE 2> /dev/null | grep '<!>'
